//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azin.Shadi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Admin
    {
        [Display(Name = "آیدی")]
        [Required(ErrorMessage = "{0} را پر کنید")]
        public int id { get; set; }

        [Display(Name = "نام")]
        [Required(ErrorMessage = "{0} را پر کنید")]
        public string Name { get; set; }

        [Display(Name = "نام خانوادگی")]
        [Required(ErrorMessage = "{0} را پر کنید")]
        public string Family { get; set; }

        [Display(Name = "نام کاربری")]
        public string Username { get; set; }

        [Display(Name = "رمز عبور")]
        [Required(ErrorMessage = "{0} را پر کنید")]
        public string Password { get; set; }

        [Display(Name = "ایمیل")]
        [EmailAddress(ErrorMessage = "ایمیل خود را به درستی وارد کنید!")]
        public string Eamil { get; set; }

        [Display(Name = "موبایل")]
        [Required(ErrorMessage = "{0} را پر کنید")]
        [RegularExpression("(09){9}[0-9]", ErrorMessage = "شماره موبایل را درست وارد کنید")]
        public string Mobile { get; set; }

        [Display(Name = "تاریخ ثبت نام")]
        [Required]
        public System.DateTime RegisterDate { get; set; }

        [Display(Name = "وضعیت")]
        [Required]
        public bool IsActive { get; set; }

        [Display(Name = "دپارتمان فعالیت")]
        [Required(ErrorMessage = "{0} را پر کنید")]
        public string Department { get; set; }

        [Display(Name = "آخرین بازدید")]
        public Nullable<System.DateTime> LastLoginDate { get; set; }

        [Display(Name = "تصویر پروفایل")]
        public string ImageName { get; set; }
    }
}
