//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azin.Shadi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Product
    {
        [Display(Name = "آیدی")]
        [Required(ErrorMessage = "{0} را پر کنید")]
        public int id { get; set; }

        [Display(Name = "نام محصول")]
        [Required(ErrorMessage = "{0} را پر کنید")]
        public string Name { get; set; }

        [Display(Name = "دسته بندی")]
        [Required(ErrorMessage = "{0} را پر کنید")]
        public string Category { get; set; }

        [Display(Name = "قیمت")]
        [Required(ErrorMessage = "{0} را پر کنید")]
        public int Price { get; set; }

        [Display(Name = "نام برند")]
        public string Brand { get; set; }

        [Display(Name = "موجودی")]
        [Required(ErrorMessage = "{0} را پر کنید")]
        public int Inventory { get; set; }

        [Display(Name = "وضعیت موجودی")]
        public bool InventoryStatus { get; set; }

        [Display(Name = "وضعیت کالا")]
        public bool IsActive { get; set; }

        [Display(Name = "تصویر کالا")]
        public string ImageName { get; set; }

        [Display(Name = "تاریخ ثبت نام")]
        [DisplayFormat(DataFormatString = "{0: dddd, dd MMMM yyyy}")]
        public System.DateTime RegisterDate { get; set; }
        
    }
}
